[package]
name = "simple-time-tracker"
version = "0.1.0"
authors = ["movalle4 <movalle4@uc.cl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
serde_json = "1.0"
csv = "1.1"